name: Deploy API to Dev GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/forward-garden-444210/locations/global/workloadIdentityPools/githuba/providers/github'
          service_account: 'githubactions@forward-garden-444210.iam.gserviceaccount.com'
    
      - name: Check gcloud
        run: |
          gcloud artifacts repositories list --project=forward-garden-444210
