name: Ci/Cd for Finch to deploy in Eks

on:
  push:
     branches:
          [ main ]

jobs:
  Infrastructure-EKS-and-RDS:
      runs-on: ubuntu-latest
      steps:
        - name: Code Checkout
          uses: actions/checkout@v5.0.0

        - name: Setup Terraform Cli
          uses: hashicorp/setup-terraform@v2.0.3

        - name: Test Terraform Installation
          working-directory: ./EKSInfra
          run: terraform init

        - name: Aws Cli Setup
          uses: isbang/setup-awscli@v0.1.0

        - name: AWS iam login
          uses: aws-actions/configure-aws-credentials@v4
          with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
              aws-region: ap-south-1 

      
