name: Ci/Cd for Finch to deploy in Eks

on:
  push:
     branches:
          [ main ]

jobs:
  Infrastructure-EKS-and-RDS:
      runs-on: ubuntu-latest
      steps:
        - name: Code Checkout
          uses: actions/checkout@v5.0.0

        - name: Setup Terraform Cli
          uses: hashicorp/setup-terraform@v2.0.3

        - name: Test Terraform Installation
          run: terraform init

      
