name: Finch CiCd


on:
  push:
     branches:
          - main
jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
     - name: Code Checkout
       uses: actions/checkout@v4

  
     - name: Install Dependencies
       run: |
            cd App
            pip install -r requirements.txt

     - name: Unit Tests
       run: |
            cd App
            pytest test_routes.py


     - name: Lint with flake8
       run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

     - name: Run tests with coverage
       run: |
          pytest --cov=your_module_name --cov-report=xml 

     - name: Install Gitleaks
       run: sudo apt install gitleaks

     - name: Run Gitleaks
       run: |
          cd App
          gitleaks detect --source .

         
  
# Run Tests

#Code quality and Codec coverage


#Owsap or gitleaks


# artifact

# nexus

#docker image


# image scan

#push to ecr

#deploy to k8s

#post nitification


